language: node_js
node_js:
  - 14

services:
  - docker


install:
  - echo "nothing needs to be installed"


before_script:
  - echo "no tests"

script:
  - docker --version
  
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed monairy/udagram-api-feed:latest
  - docker tag udagram-api-user monairy/udagram-api-user:latest
  - docker tag udagram-frontend monairy/udagram-frontend:local
  - docker tag reverseproxy monairy/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker push monairy/udagram-api-feed:latest
  - docker push monairy/udagram-api-user:latest
  - docker push monairy/udagram-frontend:local
  - docker push monairy/reverseproxy:latest