setx POSTGRES_USERNAME postgres
setx POSTGRES_PASSWORD postgres
setx POSTGRES_HOST database-1.c0cdrazlk2si.us-east-1.rds.amazonaws.com
setx POSTGRES_DB postgres
setx AWS_BUCKET arn:aws:s3:::monairy
setx AWS_REGION us-east-1
setx AWS_PROFILE default
setx JWT_SECRET testing
setx URL http://localhost:8100
